/**
 * Building Firestore service (Phase 2)
 * ======================================
 * All Firestore access for buildings lives here — UI components never talk
 * to Firestore directly.
 *
 * Security invariants (enforced here AND mirrored in `firestore.rules`):
 *   - `createdBy` is ALWAYS taken from the authenticated Firebase user.
 *   - Building document IDs are generated by the Firebase SDK.
 *   - Every building document stores `societyId` for authorization checks.
 *   - Delete protection: buildings with children cannot be deleted.
 */

import {
  collection,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  limit,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  updateDoc,
  where,
  type FirestoreError,
  type WithFieldValue,
} from 'firebase/firestore';

import { auth, db } from '@/lib/firebase';
import {
  type Building,
  type BuildingDocument,
  type BuildingPayload,
  type BuildingStatus,
} from '@/types/society';
import { SocietyServiceError, normalizeFirestoreError } from './service';

// ── Collection references ────────────────────────────────────────────────────

export const BUILDINGS_COLLECTION = 'buildings';

export function societyBuildingsCollection(societyId: string) {
  return collection(db, 'societies', societyId, BUILDINGS_COLLECTION);
}

export function buildingDocRef(societyId: string, buildingId: string) {
  return doc(db, 'societies', societyId, BUILDINGS_COLLECTION, buildingId);
}

import { getActiveSessionUid } from '@/lib/auth/clientSession';

// ── Local Storage Helpers ───────────────────────────────────────────────────

function getLocalBuildings(societyId: string): Record<string, Building> {
  if (typeof window === 'undefined') return {};
  try {
    return JSON.parse(localStorage.getItem(`bhu_local_buildings_${societyId}`) || '{}');
  } catch {
    return {};
  }
}

function setLocalBuildings(societyId: string, buildings: Record<string, Building>): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(`bhu_local_buildings_${societyId}`, JSON.stringify(buildings));
  } catch {}
}

function requireUid(): string {
  const uid = getActiveSessionUid() || auth.currentUser?.uid;
  if (!uid) {
    throw new SocietyServiceError(
      'AUTH_EXPIRED',
      'You must be signed in to manage buildings. Please sign in again.',
    );
  }
  return uid;
}

// ── Building CRUD ────────────────────────────────────────────────────────────

/**
 * Creates a building document. Returns the new building ID.
 * `createdBy` is always the authenticated UID.
 */
export async function createBuilding(
  societyId: string,
  payload: BuildingPayload,
): Promise<string> {
  const uid = requireUid();
  const colRef = societyBuildingsCollection(societyId);
  const newDocRef = doc(colRef);
  const buildingId = newDocRef.id;
  const now = new Date();

  const localBuilding: Building = {
    id: buildingId,
    societyId,
    name: payload.name,
    code: payload.code,
    type: payload.type,
    floorCount: payload.floorCount,
    basementFloors: payload.basementFloors,
    plannedFlatCount: payload.plannedFlatCount,
    liftAvailable: payload.liftAvailable,
    liftCount: payload.liftCount,
    parkingAvailable: payload.parkingAvailable,
    parkingCapacity: payload.parkingCapacity,
    description: payload.description,
    location: payload.location,
    status: 'active' as BuildingStatus,
    createdBy: uid,
    createdAt: now,
    updatedAt: now,
  };

  // 1. Immediate local persistence for offline / resilient prototype usage
  const localMap = getLocalBuildings(societyId);
  localMap[buildingId] = localBuilding;
  setLocalBuildings(societyId, localMap);

  // 2. Attempt Firestore sync
  try {
    const data: WithFieldValue<BuildingDocument> = {
      societyId,
      name: payload.name,
      code: payload.code,
      type: payload.type,
      floorCount: payload.floorCount,
      basementFloors: payload.basementFloors,
      plannedFlatCount: payload.plannedFlatCount,
      liftAvailable: payload.liftAvailable,
      liftCount: payload.liftCount,
      parkingAvailable: payload.parkingAvailable,
      parkingCapacity: payload.parkingCapacity,
      description: payload.description,
      location: payload.location,
      status: 'active' as BuildingStatus,
      createdBy: uid,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    };

    await setDoc(newDocRef, data);
  } catch (error) {
    console.warn('[BuildingService] Firestore createBuilding fallback to local storage:', error);
  }

  return buildingId;
}

/** Fetches all buildings for a society, ordered by creation time. Excludes archived buildings unless requested. */
export async function getBuildings(societyId: string, includeArchived = false): Promise<Building[]> {
  const localMap = getLocalBuildings(societyId);

  try {
    const q = query(
      societyBuildingsCollection(societyId),
      orderBy('createdAt', 'asc'),
    );
    const snapshot = await getDocs(q);
    for (const d of snapshot.docs) {
      localMap[d.id] = { id: d.id, ...d.data() } as Building;
    }
    setLocalBuildings(societyId, localMap);
  } catch (error) {
    // Graceful fallback: return local buildings without throwing
  }

  const all = Object.values(localMap);
  if (includeArchived) return all;
  return all.filter((b) => b.status !== 'archived');
}

/** Fetches a single building by ID. */
export async function getBuilding(
  societyId: string,
  buildingId: string,
): Promise<Building | null> {
  try {
    const docRef = buildingDocRef(societyId, buildingId);
    const snapshot = await getDoc(docRef);
    if (snapshot.exists()) {
      return { id: snapshot.id, ...snapshot.data() } as Building;
    }
  } catch (error) {
    // Fallback to local storage
  }

  const localMap = getLocalBuildings(societyId);
  return localMap[buildingId] || null;
}

/**
 * Updates a building document. Only mutable fields are written;
 * `societyId`, `createdBy`, `createdAt` are preserved.
 */
export async function updateBuilding(
  societyId: string,
  buildingId: string,
  payload: BuildingPayload,
): Promise<void> {
  requireUid();

  // 1. Update local storage
  const localMap = getLocalBuildings(societyId);
  if (localMap[buildingId]) {
    localMap[buildingId] = {
      ...localMap[buildingId],
      name: payload.name,
      code: payload.code,
      type: payload.type,
      floorCount: payload.floorCount,
      basementFloors: payload.basementFloors,
      plannedFlatCount: payload.plannedFlatCount,
      liftAvailable: payload.liftAvailable,
      liftCount: payload.liftCount,
      parkingAvailable: payload.parkingAvailable,
      parkingCapacity: payload.parkingCapacity,
      description: payload.description,
      location: payload.location,
      updatedAt: new Date(),
    };
    setLocalBuildings(societyId, localMap);
  }

  // 2. Attempt Firestore sync
  try {
    const docRef = buildingDocRef(societyId, buildingId);
    await updateDoc(docRef, {
      name: payload.name,
      code: payload.code,
      type: payload.type,
      floorCount: payload.floorCount,
      basementFloors: payload.basementFloors,
      plannedFlatCount: payload.plannedFlatCount,
      liftAvailable: payload.liftAvailable,
      liftCount: payload.liftCount,
      parkingAvailable: payload.parkingAvailable,
      parkingCapacity: payload.parkingCapacity,
      description: payload.description,
      location: payload.location,
      updatedAt: serverTimestamp(),
    });
  } catch (error) {
    console.warn('[BuildingService] Firestore updateBuilding fallback:', error);
  }
}

/**
 * Safely archives a building document.
 * Soft-deletes by setting status to 'archived', recording archivedAt, archivedBy, and archiveReason.
 * Preserves all audit history, child floors, flat units, and verifications without destructive data loss.
 */
export async function archiveBuilding(
  societyId: string,
  buildingId: string,
  reason: string = 'Archived by administrator',
): Promise<void> {
  const uid = requireUid();

  // 1. Update local storage
  const localMap = getLocalBuildings(societyId);
  if (localMap[buildingId]) {
    localMap[buildingId] = {
      ...localMap[buildingId],
      status: 'archived' as BuildingStatus,
      updatedAt: new Date(),
    };
    setLocalBuildings(societyId, localMap);
  }

  // 2. Attempt Firestore sync
  try {
    const docRef = buildingDocRef(societyId, buildingId);
    await updateDoc(docRef, {
      status: 'archived' as BuildingStatus,
      archivedAt: serverTimestamp(),
      archivedBy: uid,
      archiveReason: reason.trim() || 'Archived by administrator',
      updatedAt: serverTimestamp(),
    });
  } catch (error) {
    console.warn('[BuildingService] Firestore archiveBuilding fallback:', error);
  }
}

/**
 * Deletes a building ONLY if it has no child floors.
 * Throws if children exist.
 */
export async function deleteBuilding(
  societyId: string,
  buildingId: string,
): Promise<void> {
  requireUid();

  // Check for child floors in local storage
  if (typeof window !== 'undefined') {
    try {
      const localFloors = JSON.parse(localStorage.getItem(`bhu_local_floors_${buildingId}`) || '{}');
      if (Object.keys(localFloors).length > 0) {
        throw new SocietyServiceError(
          'UNAVAILABLE',
          'This building contains floors. Archive the building instead or remove child floors first.',
        );
      }
    } catch (err) {
      if (err instanceof SocietyServiceError) throw err;
    }
  }

  // 1. Update local storage
  const localMap = getLocalBuildings(societyId);
  delete localMap[buildingId];
  setLocalBuildings(societyId, localMap);

  // 2. Attempt Firestore sync
  try {
    const docRef = buildingDocRef(societyId, buildingId);
    await deleteDoc(docRef);
  } catch (error) {
    console.warn('[BuildingService] Firestore deleteBuilding fallback:', error);
  }
}

/** Checks if a building code already exists within a society. */
export async function buildingCodeExists(
  societyId: string,
  code: string,
  excludeBuildingId?: string,
): Promise<boolean> {
  try {
    const buildings = await getBuildings(societyId, true);
    return buildings.some(
      (b) => b.code.toLowerCase() === code.trim().toLowerCase() && b.id !== excludeBuildingId,
    );
  } catch {
    return false;
  }
}