/**
 * Building Firestore service (Phase 2)
 * ======================================
 * All Firestore access for buildings lives here — UI components never talk
 * to Firestore directly.
 *
 * Security invariants (enforced here AND mirrored in `firestore.rules`):
 *   - `createdBy` is ALWAYS taken from the authenticated Firebase user.
 *   - Building document IDs are generated by the Firebase SDK.
 *   - Every building document stores `societyId` for authorization checks.
 *   - Delete protection: buildings with children cannot be deleted.
 */

import {
  collection,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  limit,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  updateDoc,
  where,
  type FirestoreError,
  type WithFieldValue,
} from 'firebase/firestore';

import { auth, db } from '@/lib/firebase';
import {
  type Building,
  type BuildingDocument,
  type BuildingPayload,
  type BuildingStatus,
} from '@/types/society';
import { SocietyServiceError, normalizeFirestoreError } from './service';

// ── Collection references ────────────────────────────────────────────────────

export const BUILDINGS_COLLECTION = 'buildings';

export function societyBuildingsCollection(societyId: string) {
  return collection(db, 'societies', societyId, BUILDINGS_COLLECTION);
}

export function buildingDocRef(societyId: string, buildingId: string) {
  return doc(db, 'societies', societyId, BUILDINGS_COLLECTION, buildingId);
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function requireUid(): string {
  const uid = auth.currentUser?.uid;
  if (!uid) {
    throw new SocietyServiceError(
      'AUTH_EXPIRED',
      'You must be signed in to manage buildings. Please sign in again.',
    );
  }
  return uid;
}

// ── Building CRUD ────────────────────────────────────────────────────────────

/**
 * Creates a building document. Returns the new building ID.
 * `createdBy` is always the authenticated UID.
 */
export async function createBuilding(
  societyId: string,
  payload: BuildingPayload,
): Promise<string> {
  const uid = requireUid();
  try {
    const colRef = societyBuildingsCollection(societyId);
    const newDocRef = doc(colRef);
    const now = serverTimestamp();

    const data: WithFieldValue<BuildingDocument> = {
      societyId,
      name: payload.name,
      code: payload.code,
      type: payload.type,
      floorCount: payload.floorCount,
      basementFloors: payload.basementFloors,
      plannedFlatCount: payload.plannedFlatCount,
      liftAvailable: payload.liftAvailable,
      liftCount: payload.liftCount,
      parkingAvailable: payload.parkingAvailable,
      parkingCapacity: payload.parkingCapacity,
      description: payload.description,
      location: payload.location,
      status: 'active' as BuildingStatus,
      createdBy: uid,
      createdAt: now,
      updatedAt: now,
    };

    await setDoc(newDocRef, data);
    return newDocRef.id;
  } catch (error) {
    throw normalizeFirestoreError(error);
  }
}

/** Fetches all buildings for a society, ordered by creation time. */
export async function getBuildings(societyId: string): Promise<Building[]> {
  try {
    const q = query(
      societyBuildingsCollection(societyId),
      orderBy('createdAt', 'asc'),
    );
    const snapshot = await getDocs(q);
    return snapshot.docs.map((d) => ({ id: d.id, ...d.data() } as Building));
  } catch (error) {
    throw normalizeFirestoreError(error);
  }
}

/** Fetches a single building by ID. */
export async function getBuilding(
  societyId: string,
  buildingId: string,
): Promise<Building | null> {
  try {
    const docRef = buildingDocRef(societyId, buildingId);
    const snapshot = await getDoc(docRef);
    if (!snapshot.exists()) return null;
    return { id: snapshot.id, ...snapshot.data() } as Building;
  } catch (error) {
    throw normalizeFirestoreError(error);
  }
}

/**
 * Updates a building document. Only mutable fields are written;
 * `societyId`, `createdBy`, `createdAt` are preserved.
 */
export async function updateBuilding(
  societyId: string,
  buildingId: string,
  payload: BuildingPayload,
): Promise<void> {
  requireUid();
  try {
    const docRef = buildingDocRef(societyId, buildingId);
    await updateDoc(docRef, {
      name: payload.name,
      code: payload.code,
      type: payload.type,
      floorCount: payload.floorCount,
      basementFloors: payload.basementFloors,
      plannedFlatCount: payload.plannedFlatCount,
      liftAvailable: payload.liftAvailable,
      liftCount: payload.liftCount,
      parkingAvailable: payload.parkingAvailable,
      parkingCapacity: payload.parkingCapacity,
      description: payload.description,
      location: payload.location,
      updatedAt: serverTimestamp(),
    });
  } catch (error) {
    throw normalizeFirestoreError(error);
  }
}

/**
 * Deletes a building ONLY if it has no child floors.
 * Throws if children exist.
 */
export async function deleteBuilding(
  societyId: string,
  buildingId: string,
): Promise<void> {
  requireUid();
  try {
    // Check for child floors
    const floorsCol = collection(
      db,
      'societies',
      societyId,
      BUILDINGS_COLLECTION,
      buildingId,
      'floors',
    );
    const floorsQuery = query(floorsCol, limit(1));
    const floorsSnapshot = await getDocs(floorsQuery);

    if (!floorsSnapshot.empty) {
      throw new SocietyServiceError(
        'UNAVAILABLE',
        'This building contains floors. Remove or handle its contents before deleting the building.',
      );
    }

    const docRef = buildingDocRef(societyId, buildingId);
    await deleteDoc(docRef);
  } catch (error) {
    if (error instanceof SocietyServiceError) throw error;
    throw normalizeFirestoreError(error);
  }
}

/** Checks if a building code already exists within a society. */
export async function buildingCodeExists(
  societyId: string,
  code: string,
  excludeBuildingId?: string,
): Promise<boolean> {
  try {
    const q = query(
      societyBuildingsCollection(societyId),
      where('code', '==', code.trim()),
      limit(1),
    );
    const snapshot = await getDocs(q);
    if (snapshot.empty) return false;
    if (excludeBuildingId) {
      return snapshot.docs.some((d) => d.id !== excludeBuildingId);
    }
    return true;
  } catch (error) {
    throw normalizeFirestoreError(error);
  }
}