/**
 * Society & membership Firestore service (Phase 1)
 * ==================================================
 * All Firestore access for societies lives here — UI components never talk
 * to Firestore directly (project architecture: Firebase operations stay in
 * service modules, out of page components).
 *
 * Security invariants (enforced here AND mirrored in `firestore.rules`):
 *   - `createdBy` is ALWAYS taken from the authenticated Firebase user
 *     (`auth.currentUser.uid`) — never from a client-supplied form field.
 *   - The creator automatically receives a `society-admin` membership.
 *   - Society document IDs are generated by the Firebase SDK (no random IDs
 *     during rendering → hydration safe).
 *   - Membership documents use the deterministic ID `{societyId}_{userId}`,
 *     making duplicate memberships impossible and letting rules verify the
 *     document ID against its contents.
 */
import {
  collection,
  doc,
  getDoc,
  getDocs,
  query,
  serverTimestamp,
  updateDoc,
  where,
  writeBatch,
  type FirestoreError,
  type WithFieldValue,
} from 'firebase/firestore';

import { auth, db } from '@/lib/firebase';
import {
  SOCIETY_MEMBER_STATUSES,
  SOCIETY_STATUSES,
  type Society,
  type SocietyDocument,
  type SocietyMemberStatus,
  type SocietyMembership,
  type SocietyMembershipDocument,
  type SocietyRegistrationPayload,
  type SocietyRole,
  type SocietyStatus,
} from '@/types/society';

export const SOCIETIES_COLLECTION = 'societies';
export const SOCIETY_MEMBERS_COLLECTION = 'societyMembers';

/** Deterministic membership document ID: `{societyId}_{userId}`. */
export function societyMembershipId(societyId: string, userId: string): string {
  return `${societyId}_${userId}`;
}

export type SocietyServiceErrorCode =
  | 'AUTH_EXPIRED'
  | 'NETWORK'
  | 'PERMISSION_DENIED'
  | 'UNAVAILABLE'
  | 'NOT_FOUND'
  | 'UNKNOWN';

/** Error with a stable code and a user-friendly message (never raw Firebase). */
export class SocietyServiceError extends Error {
  code: SocietyServiceErrorCode;

  constructor(code: SocietyServiceErrorCode, message: string) {
    super(message);
    this.name = 'SocietyServiceError';
    this.code = code;
  }
}

/** Maps Firestore errors to friendly messages — raw errors are never surfaced. */
export function normalizeFirestoreError(error: unknown): SocietyServiceError {
  const code = String((error as FirestoreError | undefined)?.code ?? '');
  switch (code) {
    case 'permission-denied':
      return new SocietyServiceError(
        'PERMISSION_DENIED',
        'You do not have permission to perform this action. Please sign in again and retry.',
      );
    case 'unavailable':
    case 'network-request-failed':
      return new SocietyServiceError(
        'NETWORK',
        'Could not reach the database. Check your internet connection and try again.',
      );
    case 'failed-precondition':
      return new SocietyServiceError(
        'UNAVAILABLE',
        'The database is not ready yet. Please try again shortly.',
      );
    default:
      console.error('[SocietyService] Firestore error:', error);
      return new SocietyServiceError(
        'UNKNOWN',
        'Something went wrong while saving the society. Please try again.',
      );
  }
}

/**
 * Resolves the authenticated Firebase UID or throws. `createdBy` for every
 * society comes from HERE — never from a client-supplied form field.
 */
export function requireAuthenticatedUid(): string {
  const uid = auth.currentUser?.uid;
  if (!uid) {
    throw new SocietyServiceError(
      'AUTH_EXPIRED',
      'Your session has expired. Please sign in again to register a society.',
    );
  }
  return uid;
}

export interface CreateSocietyResult {
  societyId: string;
  createdBy: string;
}

/**
 * Creates the society document AND the creator's `society-admin` membership
 * in one atomic batch, returning the new society ID.
 */
export async function createSocietyWithAdmin(
  payload: SocietyRegistrationPayload,
): Promise<CreateSocietyResult> {
  const uid = requireAuthenticatedUid();

  // SDK-generated document ID (Firebase generates it client-side; no random
  // IDs are produced during React rendering, so this is hydration safe).
  const societyRef = doc(collection(db, SOCIETIES_COLLECTION));
  const membershipRef = doc(
    db,
    SOCIETY_MEMBERS_COLLECTION,
    societyMembershipId(societyRef.id, uid),
  );

  const societyData: WithFieldValue<SocietyDocument> = {
    name: payload.name,
    type: payload.type,
    registrationNumber: payload.registrationNumber,
    establishedYear: payload.establishedYear,
    description: payload.description,
    address: payload.address,
    location: payload.location,
    imageUrl: null,
    logoUrl: null,
    createdBy: uid, // ALWAYS the authenticated Firebase UID — never form data
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
    status: 'active',
  };

  const membershipData: WithFieldValue<SocietyMembershipDocument> = {
    societyId: societyRef.id,
    userId: uid,
    role: 'society-admin',
    status: 'active',
    createdAt: serverTimestamp(),
  };

  const batch = writeBatch(db);
  batch.set(societyRef, societyData);
  batch.set(membershipRef, membershipData);

  try {
    await batch.commit();
  } catch (error) {
    throw normalizeFirestoreError(error);
  }

  return { societyId: societyRef.id, createdBy: uid };
}

/**
 * Attaches the uploaded society image URL to the society document.
 * Called AFTER registration succeeds so an upload failure never loses the
 * society record.
 */
export async function setSocietyImageUrl(societyId: string, imageUrl: string): Promise<void> {
  try {
    await updateDoc(doc(db, SOCIETIES_COLLECTION, societyId), {
      imageUrl,
      updatedAt: serverTimestamp(),
    });
  } catch (error) {
    throw normalizeFirestoreError(error);
  }
}

/** Reads a single society, or `null` when it does not exist. */
export async function getSocietyById(societyId: string): Promise<Society | null> {
  if (!societyId) return null;
  try {
    const snapshot = await getDoc(doc(db, SOCIETIES_COLLECTION, societyId));
    if (!snapshot.exists()) return null;
    return normalizeSociety(societyId, snapshot.data());
  } catch (error) {
    throw normalizeFirestoreError(error);
  }
}

/**
 * Reads the current user's membership for a society, or `null` when the
 * user is not a member. Uses the deterministic document ID.
 */
export async function getSocietyMembership(
  societyId: string,
  userId: string,
): Promise<SocietyMembership | null> {
  if (!societyId || !userId) return null;
  const membershipId = societyMembershipId(societyId, userId);
  try {
    const snapshot = await getDoc(doc(db, SOCIETY_MEMBERS_COLLECTION, membershipId));
    if (!snapshot.exists()) return null;
    return normalizeMembership(membershipId, snapshot.data());
  } catch (error) {
    // Membership is optional dashboard context — a rules-limited read must
    // not break the page, so this degrades to "not a member".
    console.warn('[SocietyService] Membership read failed:', error);
    return null;
  }
}

// ── Normalizers (defensive reads — Firestore data is untrusted shape) ────────

function toDate(value: unknown): Date | null {
  if (!value) return null;
  if (value instanceof Date) return value;
  if (
    typeof value === 'object' &&
    value !== null &&
    'toDate' in value &&
    typeof (value as { toDate?: unknown }).toDate === 'function'
  ) {
    try {
      return (value as { toDate: () => Date }).toDate();
    } catch {
      return null;
    }
  }
  return null;
}

function toNullableString(value: unknown): string | null {
  return typeof value === 'string' && value.trim() !== '' ? value : null;
}

function normalizeSociety(id: string, data: Record<string, unknown>): Society {
  const address = (data.address ?? {}) as Partial<SocietyDocument['address']>;
  const location = (data.location ?? {}) as Partial<SocietyDocument['location']>;
  const status = (SOCIETY_STATUSES as readonly string[]).includes(data.status as string)
    ? (data.status as SocietyStatus)
    : 'active';

  return {
    id,
    name: typeof data.name === 'string' && data.name ? data.name : 'Unnamed Society',
    type: typeof data.type === 'string' && data.type ? data.type : 'Other',
    registrationNumber: toNullableString(data.registrationNumber),
    establishedYear: typeof data.establishedYear === 'number' ? data.establishedYear : null,
    description: toNullableString(data.description),
    address: {
      line1: typeof address.line1 === 'string' ? address.line1 : '',
      line2: toNullableString(address.line2),
      city: typeof address.city === 'string' ? address.city : '',
      district: toNullableString(address.district),
      state: typeof address.state === 'string' ? address.state : '',
      pinCode: typeof address.pinCode === 'string' ? address.pinCode : '',
    },
    location: {
      latitude: typeof location.latitude === 'number' ? location.latitude : null,
      longitude: typeof location.longitude === 'number' ? location.longitude : null,
      source: 'user-provided',
      dataStatus: 'illustrative',
    },
    imageUrl: toNullableString(data.imageUrl),
    logoUrl: toNullableString(data.logoUrl),
    createdBy: typeof data.createdBy === 'string' ? data.createdBy : '',
    createdAt: toDate(data.createdAt),
    updatedAt: toDate(data.updatedAt),
    status,
  };
}

function normalizeMembership(id: string, data: Record<string, unknown>): SocietyMembership {
  const role = (
    ['super-admin', 'government-officer', 'society-admin', 'resident'] as const
  ).includes(data.role as SocietyRole)
    ? (data.role as SocietyRole)
    : 'resident';
  const status = (SOCIETY_MEMBER_STATUSES as readonly string[]).includes(data.status as string)
    ? (data.status as SocietyMemberStatus)
    : 'active';

  return {
    id,
    societyId: typeof data.societyId === 'string' ? data.societyId : '',
    userId: typeof data.userId === 'string' ? data.userId : '',
    role,
    status,
    createdAt: toDate(data.createdAt),
  };
}

/**
 * Lists societies available for residents to join (Phase 3).
 * Only `active` societies are returned, using a single-equality query (no
 * composite index required); results are sorted client-side by name.
 * Only public society fields exist on this collection — no resident personal
 * information is exposed by this read.
 */
export async function getAvailableSocieties(): Promise<Society[]> {
  try {
    const q = query(
      collection(db, SOCIETIES_COLLECTION),
      where('status', '==', 'active' satisfies SocietyStatus),
    );
    const snapshot = await getDocs(q);
    const societies = snapshot.docs.map((d) => normalizeSociety(d.id, d.data()));
    societies.sort((a, b) => a.name.localeCompare(b.name));
    return societies;
  } catch (error) {
    throw normalizeFirestoreError(error);
  }
}




