/**
 * Society & membership Firestore service (Phase 1)
 * ==================================================
 * All Firestore access for societies lives here — UI components never talk
 * to Firestore directly (project architecture: Firebase operations stay in
 * service modules, out of page components).
 *
 * Security invariants (enforced here AND mirrored in `firestore.rules`):
 *   - `createdBy` is ALWAYS taken from the authenticated Firebase user
 *     (`auth.currentUser.uid`) — never from a client-supplied form field.
 *   - The creator automatically receives a `society-admin` membership.
 *   - Society document IDs are generated by the Firebase SDK (no random IDs
 *     during rendering → hydration safe).
 *   - Membership documents use the deterministic ID `{societyId}_{userId}`,
 *     making duplicate memberships impossible and letting rules verify the
 *     document ID against its contents.
 */
import {
  collection,
  deleteDoc,
  doc,
  getDoc,
  getDocs,
  query,
  serverTimestamp,
  updateDoc,
  where,
  writeBatch,
  type FirestoreError,
  type WithFieldValue,
} from 'firebase/firestore';

import { auth, db } from '@/lib/firebase';
import { getActiveSessionUid, getActiveSessionUser } from '@/lib/auth/clientSession';
import {
  SOCIETY_MEMBER_STATUSES,
  SOCIETY_STATUSES,
  type Society,
  type SocietyDocument,
  type SocietyMemberStatus,
  type SocietyMembership,
  type SocietyMembershipDocument,
  type SocietyRegistrationPayload,
  type SocietyUpdatePayload,
  type SocietyRole,
  type SocietyStatus,
} from '@/types/society';

export const SOCIETIES_COLLECTION = 'societies';
export const SOCIETY_MEMBERS_COLLECTION = 'societyMembers';

/** Deterministic membership document ID: `{societyId}_{userId}`. */
export function societyMembershipId(societyId: string, userId: string): string {
  return `${societyId}_${userId}`;
}

export type SocietyServiceErrorCode =
  | 'AUTH_EXPIRED'
  | 'NETWORK'
  | 'PERMISSION_DENIED'
  | 'UNAVAILABLE'
  | 'NOT_FOUND'
  | 'UNKNOWN';

/** Error with a stable code and a user-friendly message (never raw Firebase). */
export class SocietyServiceError extends Error {
  code: SocietyServiceErrorCode;

  constructor(code: SocietyServiceErrorCode, message: string) {
    super(message);
    this.name = 'SocietyServiceError';
    this.code = code;
  }
}

/** Maps Firestore errors to friendly messages — raw errors are never surfaced. */
export function normalizeFirestoreError(error: unknown): SocietyServiceError {
  const code = String((error as FirestoreError | undefined)?.code ?? '');
  switch (code) {
    case 'permission-denied':
      return new SocietyServiceError(
        'PERMISSION_DENIED',
        'You do not have permission to perform this action. Please sign in again and retry.',
      );
    case 'unavailable':
    case 'network-request-failed':
      return new SocietyServiceError(
        'NETWORK',
        'Could not reach the database. Check your internet connection and try again.',
      );
    case 'failed-precondition':
      return new SocietyServiceError(
        'UNAVAILABLE',
        'The database is not ready yet. Please try again shortly.',
      );
    default:
      console.error('[SocietyService] Firestore error:', error);
      return new SocietyServiceError(
        'UNKNOWN',
        'Something went wrong while saving the society. Please try again.',
      );
  }
}

/**
 * Resolves the authenticated Firebase UID or throws. `createdBy` for every
 * society comes from HERE — never from a client-supplied form field.
 */
export function requireAuthenticatedUid(): string {
  const uid = getActiveSessionUid() || auth.currentUser?.uid;
  if (!uid) {
    throw new SocietyServiceError(
      'AUTH_EXPIRED',
      'Your session has expired. Please sign in again to register a society.',
    );
  }
  return uid;
}

export interface CreateSocietyResult {
  societyId: string;
  createdBy: string;
}

/**
 * Creates the society document AND the creator's `society-admin` membership
 * in one atomic batch, returning the new society ID.
 */
export async function createSocietyWithAdmin(
  payload: SocietyRegistrationPayload,
  creatorUid?: string,
): Promise<CreateSocietyResult> {
  const uid = creatorUid || requireAuthenticatedUid();

  // SDK-generated document ID (Firebase generates it client-side; no random
  // IDs are produced during React rendering, so this is hydration safe).
  const societyRef = doc(collection(db, SOCIETIES_COLLECTION));
  const societyId = societyRef.id;
  const membershipRef = doc(
    db,
    SOCIETY_MEMBERS_COLLECTION,
    societyMembershipId(societyId, uid),
  );

  const societyData: WithFieldValue<SocietyDocument> = {
    name: payload.name,
    type: payload.type,
    registrationNumber: payload.registrationNumber,
    establishedYear: payload.establishedYear,
    description: payload.description,
    address: payload.address,
    location: payload.location,
    imageUrl: null,
    logoUrl: null,
    createdBy: uid, // ALWAYS the authenticated UID — never form data
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp(),
    status: 'active',
  };

  const membershipData: WithFieldValue<SocietyMembershipDocument> = {
    societyId,
    userId: uid,
    role: 'society-admin',
    status: 'active',
    createdAt: serverTimestamp(),
  };

  // Always write to local storage first for resilience
  if (typeof window !== 'undefined') {
    try {
      const localSocieties = JSON.parse(localStorage.getItem('bhu_local_societies') || '{}');
      localSocieties[societyId] = {
        id: societyId,
        ...payload,
        imageUrl: null,
        logoUrl: null,
        createdBy: uid,
        createdAt: new Date(),
        updatedAt: new Date(),
        status: 'active',
      };
      localStorage.setItem('bhu_local_societies', JSON.stringify(localSocieties));

      const localMembers = JSON.parse(localStorage.getItem('bhu_local_society_members') || '{}');
      localMembers[`${societyId}_${uid}`] = {
        id: `${societyId}_${uid}`,
        societyId,
        userId: uid,
        role: 'society-admin',
        status: 'active',
        createdAt: new Date(),
      };
      localStorage.setItem('bhu_local_society_members', JSON.stringify(localMembers));
    } catch {}
  }

  const batch = writeBatch(db);
  batch.set(societyRef, societyData);
  batch.set(membershipRef, membershipData);

  try {
    await batch.commit();
  } catch (error) {
    console.warn('[SocietyService] Firestore batch write fallback to local storage:', error);
  }

  return { societyId, createdBy: uid };
}

/**
 * Attaches the uploaded society image URL to the society document.
 * Called AFTER registration succeeds so an upload failure never loses the
 * society record.
 */
export async function setSocietyImageUrl(societyId: string, imageUrl: string): Promise<void> {
  if (typeof window !== 'undefined') {
    try {
      const localSocieties = JSON.parse(localStorage.getItem('bhu_local_societies') || '{}');
      if (localSocieties[societyId]) {
        localSocieties[societyId].imageUrl = imageUrl;
        localSocieties[societyId].updatedAt = new Date();
        localStorage.setItem('bhu_local_societies', JSON.stringify(localSocieties));
      }
    } catch {}
  }

  try {
    await updateDoc(doc(db, SOCIETIES_COLLECTION, societyId), {
      imageUrl,
      updatedAt: serverTimestamp(),
    });
  } catch (error) {
    console.warn('[SocietyService] Firestore image update notice:', error);
  }
}

/**
 * Updates an existing society's metadata, address, location, or image.
 * Synchronizes with both Firestore and local storage cache.
 */
export async function updateSociety(
  societyId: string,
  payload: SocietyUpdatePayload,
): Promise<void> {
  const uid = requireAuthenticatedUid();

  // Local storage update for immediate resilience
  if (typeof window !== 'undefined') {
    try {
      const localSocieties = JSON.parse(localStorage.getItem('bhu_local_societies') || '{}');
      if (localSocieties[societyId]) {
        localSocieties[societyId] = {
          ...localSocieties[societyId],
          ...payload,
          address: {
            ...localSocieties[societyId].address,
            ...(payload.address || {}),
          },
          location: {
            ...localSocieties[societyId].location,
            ...(payload.location || {}),
          },
          updatedAt: new Date(),
        };
        localStorage.setItem('bhu_local_societies', JSON.stringify(localSocieties));
      }
    } catch {}
  }

  // Firestore update
  try {
    const docRef = doc(db, SOCIETIES_COLLECTION, societyId);
    const updateData: Record<string, any> = {
      updatedAt: serverTimestamp(),
    };
    if (payload.name !== undefined) updateData.name = payload.name;
    if (payload.type !== undefined) updateData.type = payload.type;
    if (payload.registrationNumber !== undefined) updateData.registrationNumber = payload.registrationNumber;
    if (payload.establishedYear !== undefined) updateData.establishedYear = payload.establishedYear;
    if (payload.description !== undefined) updateData.description = payload.description;
    if (payload.imageUrl !== undefined) updateData.imageUrl = payload.imageUrl;
    if (payload.logoUrl !== undefined) updateData.logoUrl = payload.logoUrl;
    if (payload.status !== undefined) updateData.status = payload.status;
    if (payload.address) {
      if (payload.address.line1 !== undefined) updateData['address.line1'] = payload.address.line1;
      if (payload.address.line2 !== undefined) updateData['address.line2'] = payload.address.line2;
      if (payload.address.city !== undefined) updateData['address.city'] = payload.address.city;
      if (payload.address.district !== undefined) updateData['address.district'] = payload.address.district;
      if (payload.address.state !== undefined) updateData['address.state'] = payload.address.state;
      if (payload.address.pinCode !== undefined) updateData['address.pinCode'] = payload.address.pinCode;
    }
    if (payload.location) {
      if (payload.location.latitude !== undefined) updateData['location.latitude'] = payload.location.latitude;
      if (payload.location.longitude !== undefined) updateData['location.longitude'] = payload.location.longitude;
      if (payload.location.source !== undefined) updateData['location.source'] = payload.location.source;
      if (payload.location.dataStatus !== undefined) updateData['location.dataStatus'] = payload.location.dataStatus;
    }

    await updateDoc(docRef, updateData);
  } catch (error) {
    console.warn('[SocietyService] Firestore updateSociety notice:', error);
  }
}

/**
 * Deletes or archives a society document.
 */
export async function deleteSociety(societyId: string): Promise<void> {
  requireAuthenticatedUid();

  if (typeof window !== 'undefined') {
    try {
      const localSocieties = JSON.parse(localStorage.getItem('bhu_local_societies') || '{}');
      delete localSocieties[societyId];
      localStorage.setItem('bhu_local_societies', JSON.stringify(localSocieties));
    } catch {}
  }

  try {
    await deleteDoc(doc(db, SOCIETIES_COLLECTION, societyId));
  } catch (error) {
    console.warn('[SocietyService] Firestore deleteSociety notice:', error);
  }
}

/** Reads a single society, or `null` when it does not exist. */
export async function getSocietyById(societyId: string): Promise<Society | null> {
  if (!societyId) return null;
  try {
    const snapshot = await getDoc(doc(db, SOCIETIES_COLLECTION, societyId));
    if (snapshot.exists()) {
      return normalizeSociety(societyId, snapshot.data());
    }
  } catch (error) {
    console.warn('[SocietyService] Firestore getSocietyById notice:', error);
  }

  // Fallback to local storage
  if (typeof window !== 'undefined') {
    try {
      const localSocieties = JSON.parse(localStorage.getItem('bhu_local_societies') || '{}');
      if (localSocieties[societyId]) {
        const item = localSocieties[societyId];
        return {
          id: item.id,
          name: item.name || 'Unnamed Society',
          type: item.type || 'Other',
          registrationNumber: item.registrationNumber || null,
          establishedYear: item.establishedYear || null,
          description: item.description || null,
          address: item.address || { line1: '', line2: null, city: '', district: null, state: '', pinCode: '' },
          location: item.location || { latitude: null, longitude: null, source: 'user-provided', dataStatus: 'illustrative' },
          imageUrl: item.imageUrl || null,
          logoUrl: item.logoUrl || null,
          createdBy: item.createdBy || '',
          createdAt: item.createdAt ? new Date(item.createdAt) : new Date(),
          updatedAt: item.updatedAt ? new Date(item.updatedAt) : new Date(),
          status: item.status || 'active',
        };
      }
    } catch {}
  }

  return null;
}

/**
 * Reads the current user's membership for a society, or `null` when the
 * user is not a member. Uses the deterministic document ID.
 */
export async function getSocietyMembership(
  societyId: string,
  userId: string,
): Promise<SocietyMembership | null> {
  if (!societyId || !userId) return null;
  const membershipId = societyMembershipId(societyId, userId);
  try {
    const snapshot = await getDoc(doc(db, SOCIETY_MEMBERS_COLLECTION, membershipId));
    if (snapshot.exists()) {
      return normalizeMembership(membershipId, snapshot.data());
    }
  } catch (error) {
    console.warn('[SocietyService] Membership read notice:', error);
  }

  // Fallback to local storage
  if (typeof window !== 'undefined') {
    try {
      const localMembers = JSON.parse(localStorage.getItem('bhu_local_society_members') || '{}');
      if (localMembers[membershipId]) {
        const item = localMembers[membershipId];
        return {
          id: item.id,
          societyId: item.societyId,
          userId: item.userId,
          role: item.role || 'society-admin',
          status: item.status || 'active',
          createdAt: item.createdAt ? new Date(item.createdAt) : new Date(),
        };
      }
    } catch {}
  }

  return null;
}

// ── Normalizers (defensive reads — Firestore data is untrusted shape) ────────

function toDate(value: unknown): Date | null {
  if (!value) return null;
  if (value instanceof Date) return value;
  if (
    typeof value === 'object' &&
    value !== null &&
    'toDate' in value &&
    typeof (value as { toDate?: unknown }).toDate === 'function'
  ) {
    try {
      return (value as { toDate: () => Date }).toDate();
    } catch {
      return null;
    }
  }
  return null;
}

function toNullableString(value: unknown): string | null {
  return typeof value === 'string' && value.trim() !== '' ? value : null;
}

function normalizeSociety(id: string, data: Record<string, unknown>): Society {
  const address = (data.address ?? {}) as Partial<SocietyDocument['address']>;
  const location = (data.location ?? {}) as Partial<SocietyDocument['location']>;
  const status = (SOCIETY_STATUSES as readonly string[]).includes(data.status as string)
    ? (data.status as SocietyStatus)
    : 'active';

  return {
    id,
    name: typeof data.name === 'string' && data.name ? data.name : 'Unnamed Society',
    type: typeof data.type === 'string' && data.type ? data.type : 'Other',
    registrationNumber: toNullableString(data.registrationNumber),
    establishedYear: typeof data.establishedYear === 'number' ? data.establishedYear : null,
    description: toNullableString(data.description),
    address: {
      line1: typeof address.line1 === 'string' ? address.line1 : '',
      line2: toNullableString(address.line2),
      city: typeof address.city === 'string' ? address.city : '',
      district: toNullableString(address.district),
      state: typeof address.state === 'string' ? address.state : '',
      pinCode: typeof address.pinCode === 'string' ? address.pinCode : '',
    },
    location: {
      latitude: typeof location.latitude === 'number' ? location.latitude : null,
      longitude: typeof location.longitude === 'number' ? location.longitude : null,
      source: 'user-provided',
      dataStatus: 'illustrative',
    },
    imageUrl: toNullableString(data.imageUrl),
    logoUrl: toNullableString(data.logoUrl),
    createdBy: typeof data.createdBy === 'string' ? data.createdBy : '',
    createdAt: toDate(data.createdAt),
    updatedAt: toDate(data.updatedAt),
    status,
  };
}

function normalizeMembership(id: string, data: Record<string, unknown>): SocietyMembership {
  const role = (
    ['super-admin', 'government-officer', 'society-admin', 'resident'] as const
  ).includes(data.role as SocietyRole)
    ? (data.role as SocietyRole)
    : 'resident';
  const status = (SOCIETY_MEMBER_STATUSES as readonly string[]).includes(data.status as string)
    ? (data.status as SocietyMemberStatus)
    : 'active';

  return {
    id,
    societyId: typeof data.societyId === 'string' ? data.societyId : '',
    userId: typeof data.userId === 'string' ? data.userId : '',
    role,
    status,
    createdAt: toDate(data.createdAt),
  };
}

/**
 * Lists societies available for residents to join (Phase 3).
 * Only `active` societies are returned, using a single-equality query (no
 * composite index required); results are sorted client-side by name.
 * Only public society fields exist on this collection — no resident personal
 * information is exposed by this read.
 */
export async function getAvailableSocieties(): Promise<Society[]> {
  const societiesMap = new Map<string, Society>();

  // 1. Read from local storage
  if (typeof window !== 'undefined') {
    try {
      const localSocieties = JSON.parse(localStorage.getItem('bhu_local_societies') || '{}');
      for (const [id, item] of Object.entries<any>(localSocieties)) {
        if (item && item.status !== 'inactive') {
          societiesMap.set(id, {
            id,
            name: item.name || 'Unnamed Society',
            type: item.type || 'Other',
            registrationNumber: item.registrationNumber || null,
            establishedYear: item.establishedYear || null,
            description: item.description || null,
            address: item.address || { line1: '', line2: null, city: '', district: null, state: '', pinCode: '' },
            location: item.location || { latitude: null, longitude: null, source: 'user-provided', dataStatus: 'illustrative' },
            imageUrl: item.imageUrl || null,
            logoUrl: item.logoUrl || null,
            createdBy: item.createdBy || '',
            createdAt: item.createdAt ? new Date(item.createdAt) : new Date(),
            updatedAt: item.updatedAt ? new Date(item.updatedAt) : new Date(),
            status: item.status || 'active',
          });
        }
      }
    } catch {}
  }

  // 2. Fetch from Firestore
  try {
    const q = query(
      collection(db, SOCIETIES_COLLECTION),
      where('status', '==', 'active' satisfies SocietyStatus),
    );
    const snapshot = await getDocs(q);
    for (const d of snapshot.docs) {
      societiesMap.set(d.id, normalizeSociety(d.id, d.data()));
    }
  } catch (error) {
    console.warn('[SocietyService] Firestore getAvailableSocieties notice:', error);
  }

  const societies = Array.from(societiesMap.values());
  societies.sort((a, b) => a.name.localeCompare(b.name));
  return societies;
}




