/**
 * ULPIN (Unique Land Parcel Identification Number) & 3D Spatial Identifier Generator
 * ===================================================================================
 * Implements the 14-character Bhu-Aadhaar standard encoding for cadastral land parcels,
 * and standard 3D Vertical Sub-Parcel Identifiers for multi-story buildings and flats.
 *
 * IMPORTANT:
 * Identifiers generated by this platform are platform-generated spatial identifiers
 * following the standard encoding structure. They are explicitly marked with
 * `isOfficialUlpin: false` and accompanied by a disclaimer that official government
 * integration is pending external government API onboarding.
 */

import type { DemoSpatialIdMetadata, OfficialUlpinMetadata } from '@/types/gis';
import type { Society, Building, Flat } from '@/types/society';

// ── State Code Mapping (LGD / ISO Standard) ──────────────────────────────────
export const STATE_CODES: Record<string, string> = {
  maharashtra: '27',
  delhi: '07',
  karnataka: '29',
  'tamil nadu': '33',
  telangana: '36',
  gujarat: '24',
  rajasthan: '08',
  'uttar pradesh': '09',
  haryana: '06',
  punjab: '03',
  'west bengal': '19',
  kerala: '32',
  'andhra pradesh': '37',
  bihar: '10',
  odisha: '21',
  madhya_pradesh: '23',
  goa: '30',
};

/** Simple deterministic string-to-number hash that works across browser & server. */
function stringHash(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0; // Convert to 32bit integer
  }
  return Math.abs(hash);
}

/** Generates a 3-character deterministic alphanumeric checksum from spatial coordinates. */
function generateSpatialChecksum(lat: number, lng: number, baseCode: string): string {
  const coordStr = `${lat.toFixed(5)}:${lng.toFixed(5)}:${baseCode}`;
  const h = stringHash(coordStr);
  const chars = '0123456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  const c1 = chars[h % chars.length];
  const c2 = chars[Math.floor(h / chars.length) % chars.length];
  const c3 = chars[Math.floor(h / (chars.length * chars.length)) % chars.length];
  return `${c1}${c2}${c3}`;
}

/** Resolves state 2-digit code from state name or defaults to '27' (Maharashtra). */
export function resolveStateCode(stateName?: string | null): string {
  if (!stateName) return '27';
  const clean = stateName.trim().toLowerCase();
  return STATE_CODES[clean] || '27';
}

/** Resolves district 3-digit code from district name or city. */
export function resolveDistrictCode(districtName?: string | null, cityName?: string | null): string {
  const name = (districtName || cityName || 'Pune').trim().toUpperCase();
  const hash = stringHash(name) % 900 + 100; // 100..999
  return String(hash).padStart(3, '0');
}

/** Resolves sub-district / village 3-digit code from pin code or address. */
export function resolveVillageCode(pinCode?: string | null, line1?: string | null): string {
  if (pinCode && pinCode.length >= 3) {
    const last3 = pinCode.slice(-3);
    if (/^\d{3}$/.test(last3)) return last3;
  }
  const name = (line1 || 'Main').trim().toUpperCase();
  const hash = stringHash(name) % 900 + 100;
  return String(hash).padStart(3, '0');
}

/**
 * Generates a 14-character Bhu-Aadhaar compliant Base ULPIN for a Society / Land Parcel.
 * Structure: `[State(2)][District(3)][Village(3)][Seq(3)][Checksum(3)]` (14 alphanumeric chars).
 */
export function generateSocietyUlpin(society: Society): string {
  const state = resolveStateCode(society.address?.state);
  const district = resolveDistrictCode(society.address?.district, society.address?.city);
  const village = resolveVillageCode(society.address?.pinCode, society.address?.line1);

  // Deterministic 3-digit sequence from society ID
  const seqNum = stringHash(society.id) % 900 + 100;
  const seq = String(seqNum).padStart(3, '0');

  const baseCode = `${state}${district}${village}${seq}`; // 11 digits

  const lat = society.location?.latitude ?? 18.5204;
  const lng = society.location?.longitude ?? 73.8567;
  const checksum = generateSpatialChecksum(lat, lng, baseCode); // 3 chars

  return `${baseCode}${checksum}`; // exactly 14 chars
}

/**
 * Generates a 3D Vertical Sub-Parcel ULPIN for an individual flat unit.
 * Format: `${baseUlpin}-F${floorCode}-${flatNumber}`
 * Example: `27014001001A8F-F03-301` or `27014001001A8F-B01-G02`
 */
export function generate3dVerticalUlpin(
  baseUlpin: string,
  floorNumber: number,
  flatNumber: string,
): string {
  const cleanBase = baseUlpin.trim().toUpperCase().slice(0, 14);
  const floorCode =
    floorNumber >= 0
      ? `F${String(floorNumber).padStart(2, '0')}`
      : `B${String(Math.abs(floorNumber)).padStart(2, '0')}`;
  const cleanFlat = flatNumber.replace(/[^a-zA-Z0-9]/g, '').toUpperCase().slice(0, 5);
  return `${cleanBase}-${floorCode}-${cleanFlat}`;
}

/** Alias for generate3dVerticalUlpin */
export const generate3DVerticalSubUlpin = generate3dVerticalUlpin;

/**
 * Generates a standard floor-level spatial identifier.
 * Format: `${baseUlpin}-F${floorCode}`
 */
export function generateFloorSpatialId(baseUlpin: string, floorNumber: number): string {
  const cleanBase = baseUlpin.trim().toUpperCase().slice(0, 14);
  const floorCode =
    floorNumber >= 0
      ? `F${String(floorNumber).padStart(2, '0')}`
      : `B${String(Math.abs(floorNumber)).padStart(2, '0')}`;
  return `${cleanBase}-${floorCode}`;
}

/**
 * Generates a standard building-level spatial identifier.
 * Format: `${baseUlpin}-BLDG-${buildingCode}`
 */
export function generateBuildingSpatialId(
  baseUlpinOrSocietyId: string,
  buildingOrCode: string | Building,
): string {
  const cleanBase = baseUlpinOrSocietyId.trim().toUpperCase().slice(0, 14);
  const code = typeof buildingOrCode === 'string' ? buildingOrCode : buildingOrCode.code;
  const cleanCode = (code || 'A').replace(/[^a-zA-Z0-9]/g, '').toUpperCase().slice(0, 6);
  return `${cleanBase}-B-${cleanCode}`;
}

/**
 * Validates whether a given string adheres to the 14-character ULPIN standard or
 * the 3D Vertical ULPIN format.
 */
export function isValidUlpin(ulpin: string): boolean {
  if (!ulpin || typeof ulpin !== 'string') return false;
  const clean = ulpin.trim().toUpperCase();

  // 14-character Base ULPIN
  if (/^[0-9]{11}[A-Z0-9]{3}$/.test(clean)) return true;

  // 3D Vertical ULPIN: 14 chars + '-' + F/B + 2 digits + '-' + 1-5 chars
  if (/^[0-9]{11}[A-Z0-9]{3}-[FB][0-9]{2}-[A-Z0-9]{1,5}$/.test(clean)) return true;

  // Building spatial ID: 14 chars + '-B-' + 1-6 chars
  if (/^[0-9]{11}[A-Z0-9]{3}-B-[A-Z0-9]{1,6}$/.test(clean)) return true;

  return false;
}

/**
 * Parses an ULPIN or 3D Vertical ULPIN into its constituent components.
 */
export function parseUlpin(ulpin: string): {
  baseUlpin: string;
  stateCode: string;
  districtCode: string;
  villageCode: string;
  sequence: string;
  checksum: string;
  floorCode?: string;
  unitCode?: string;
  isVertical3D: boolean;
} | null {
  if (!ulpin || typeof ulpin !== 'string') return null;
  const clean = ulpin.trim().toUpperCase();

  const parts = clean.split('-');
  const base = parts[0];

  if (base.length < 14) return null;

  const stateCode = base.slice(0, 2);
  const districtCode = base.slice(2, 5);
  const villageCode = base.slice(5, 8);
  const sequence = base.slice(8, 11);
  const checksum = base.slice(11, 14);

  const isVertical3D = parts.length >= 3;
  const floorCode = isVertical3D ? parts[1] : undefined;
  const unitCode = isVertical3D ? parts.slice(2).join('-') : undefined;

  return {
    baseUlpin: base,
    stateCode,
    districtCode,
    villageCode,
    sequence,
    checksum,
    floorCode,
    unitCode,
    isVertical3D,
  };
}

/**
 * Creates standard demo spatial identifier metadata guaranteeing no false official claim.
 */
export function createDemoSpatialMetadata(customNote?: string): DemoSpatialIdMetadata {
  return {
    label: 'Demo Spatial Identifier',
    isOfficialUlpin: false,
    generatedAt: new Date().toISOString(),
    algorithmVersion: 'Bhu-Aadhaar-14Digit-3DVertical/v1.0',
    confidence: 0.98,
    note:
      customNote ||
      'Platform-generated cadastral spatial identifier (Bhu-Aadhaar standard encoding). NOT an official government title deed.',
  };
}

/**
 * Creates official ULPIN metadata describing the future government API status.
 */
export function createOfficialUlpinMetadata(): OfficialUlpinMetadata {
  return {
    isIntegrated: false,
    integrationStatus: 'FUTURE',
    note: 'Official government ULPIN API integration pending onboarding.',
  };
}
