/**
 * Unified GIS Data Model Types
 * =================================
 * Core entities for the 3D ULPIN Generation and Vertical Property Mapping System.
 *
 * IMPORTANT: The `PropertyUnit` defined here is a GIS-level vertical property
 * unit. It is DISTINCT from the `PropertyUnit` type in `types/index.ts`
 * (which is a floor-level residential/commercial unit embedded inside
 * `BuildingStructure`). They coexist without conflict because they live in
 * separate modules.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Geometry primitives
// ─────────────────────────────────────────────────────────────────────────────

/** WGS-84 geographic coordinate. */
export interface GeoCoordinate {
  lat: number;
  lng: number;
}

/**
 * GeoJSON-style geometry envelope.
 * The `coordinates` array shape depends on `type`:
 *   - Point        → [number, number]
 *   - LineString   → [number, number][]
 *   - Polygon      → [number, number][][]
 *   - MultiPolygon → [number, number][][][]
 */
export interface Geometry {
  type: 'Polygon' | 'Point' | 'LineString' | 'MultiPolygon';
  coordinates: number[] | number[][] | number[][][] | number[][][][];
}

// ─────────────────────────────────────────────────────────────────────────────
// Demo Spatial Identifier metadata
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Metadata that accompanies every `demoSpatialId` on a PropertyUnit.
 *
 * The demo spatial identifier is generated by the platform's own 3D
 * extraction pipeline. It is **NOT** an official, legally-valid ULPIN. The
 * field `isOfficialUlpin: false` is a hard guarantee baked into the type
 * system so that no consumer can mistake it for an official ULPIN.
 */
export interface DemoSpatialIdMetadata {
  label: 'Demo Spatial Identifier';
  /** Always `false` — the demo ID is NOT a legally-valid ULPIN. */
  isOfficialUlpin: false;
  /** ISO timestamp when the demo spatial ID was first generated. */
  generatedAt: string;
  /** Version of the 3D extraction / spatial-ID algorithm. */
  algorithmVersion: string;
    /** Confidence score 0–1 from the AI extraction pipeline. */
  confidence: number;
  /** Human-readable note clarifying the non-official nature. */
  note: string;
}

/**
 * Metadata describing the future official ULPIN integration.
 *
 * Official ULPIN integration is represented as a **Future / External
 * Government API Integration**. Until the government ULPIN API is available
 * and onboarded, `isIntegrated` remains `false` and
 * `officialUlpinReference` on the PropertyUnit stays `null`.
 */
export interface OfficialUlpinMetadata {
  /** Always `false` until the government API is live. */
  isIntegrated: false;
  integrationStatus: 'FUTURE' | 'EXTERNAL_GOVERNMENT_API';
  /** API endpoint that will serve official ULPINs once live. */
  apiEndpoint?: string;
  /** Human-readable note about the integration roadmap. */
  note: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Status enums
// ─────────────────────────────────────────────────────────────────────────────

export type ParcelStatus = 'ACTIVE' | 'INACTIVE' | 'DISPUTED';

export type BuildingStatus = 'ACTIVE' | 'INACTIVE' | 'UNDER_CONSTRUCTION';

/**
 * Property-level verification status used throughout the unified GIS model.
 *
 * NOTE: This is intentionally different from the legacy `VerificationStatus`
 * in `types/index.ts` (SUBMITTED / UNDER_REVIEW / etc.). The GIS model uses
 * human-readable labels that map 1:1 to the verification lifecycle described
 * in Phase 1.
 */
export type PropertyVerificationStatus =
  | 'Pending'
  | 'Under Review'
  | 'Field Verification'
  | 'Verified'
  | 'Rejected'
  | 'Reinspection Required';

/** Data source for a PropertyUnit record. */
export type DataSource =
  | 'SURVEY_RECORD'
  | 'DRONE_SCAN'
  | 'AI_EXTRACTION'
  | 'MANUAL_INPUT';

/** Property type at the GIS vertical-property level. */
export type PropertyTypeGis =
  | 'RESIDENTIAL'
  | 'COMMERCIAL'
  | 'INDUSTRIAL'
  | 'AGRICULTURAL'
  | 'MIXED_USE'
  | 'GOVERNMENT';

// ─────────────────────────────────────────────────────────────────────────────
// Core entities
// ─────────────────────────────────────────────────────────────────────────────

/** A cadastral land parcel (a registered plot of land). */
export interface LandParcel {
  id: string;
  parcelNumber: string;
  location: string;
  district: string;
  state: string;
  /** Area in square metres. */
  area: number;
  geometry: Geometry;
  centroid: GeoCoordinate;
  latitude: number;
  longitude: number;
  status: ParcelStatus;
  createdAt: string;
  updatedAt: string;
}

/** A building that sits on a land parcel. */
export interface Building {
  id: string;
  buildingCode: string;
  name: string;
  parcelId: string;
  address: string;
  latitude: number;
  longitude: number;
  /** Height in metres from ground level to architectural crown. */
  height: number;
  totalFloors: number;
  /** Total built-up area in square feet. */
  builtUpArea: number;
  yearBuilt: number;
  geometry: Geometry;
  status: BuildingStatus;
}

/** A single floor within a building. */
export interface Floor {
  id: string;
  buildingId: string;
  /** 0 = ground, negative = basement, positive = above-ground. */
  floorNumber: number;
  name: string;
  /** Elevation of the floor slab in metres. */
  elevation: number;
  /** Carpet / floor area in square feet. */
  area: number;
  totalUnits: number;
}

/**
 * A vertical (street-to-sky) property unit — the smallest addressable
 * cadastral object in the 3D ULPIN system.
 *
 * The `demoSpatialId` field carries a **Demo Spatial Identifier** (not an
 * official ULPIN). `officialUlpinReference` is `null` until the government
 * ULPIN API is integrated.
 */
export interface PropertyUnit {
  id: string;
  /** External property reference used by the existing PropertyItem system. */
  propertyId: string;
  /**
   * Demo Spatial Identifier — NOT an official legally-valid ULPIN.
   * Example: `3D-MH-PUN-102-301`
   */
  demoSpatialId: string;
  /**
   * Official ULPIN reference. `null` until the government API is integrated.
   */
  officialUlpinReference: string | null;
  buildingId: string;
  floorId: string;
  parcelId: string;
  /** Human-readable unit label, e.g. `0301` or `G-01`. */
  unitNumber: string;
  propertyType: PropertyTypeGis;
  /** Area in square feet. */
  area: number;
  latitude: number;
  longitude: number;
  /** Elevation of the unit centroid in metres. */
  elevation: number;
  geometry: Geometry;
  /** Owner name (reference / lookup, not a full KYC). */
  ownerReferenceName: string;
  verificationStatus: PropertyVerificationStatus;
  lastUpdated: string;
  dataSource: DataSource;

  /** Metadata proving this is a demo, non-official spatial ID. */
  demoSpatialIdMetadata: DemoSpatialIdMetadata;
  /** Metadata about the future official ULPIN integration. */
  officialUlpinMetadata: OfficialUlpinMetadata;
}

/**
 * Standalone demo spatial identifier record (1:1 with a PropertyUnit).
 * Provides richer metadata about the extraction algorithm and confidence.
 */
export interface DemoSpatialIdentifier {
  id: string;
  propertyUnitId: string;
  demoId: string;
  algorithm: string;
  confidence: number;
  /** Always `false` — explicitly not an official ULPIN. */
  isOfficial: false;
  generatedAt: string;
  note: string;
}

/** Reference descriptor for the future official ULPIN API. */
export interface UlpinReference {
  ulpin: string;
  dataSource: 'FUTURE_GOVERNMENT_API';
  status: 'NOT_INTEGRATED';
  note: string;
}
