-- Seed: Demo Spatial IDs (Phase 13)
-- Generates one demo spatial ID record per property unit via INSERT...SELECT.
-- Each record is explicitly marked is_official = false.
begin;

insert into demo_spatial_ids
  (property_unit_id, demo_id, algorithm, confidence, is_official, generated_at, note)
select
  id,
  demo_spatial_id,
  '3D-ULPIN/v2.4-spatial-hash',
  confidence,
  false,
  generated_at,
  'Demo spatial identifier — NOT an official ULPIN. Generated by AI 3D extraction pipeline.'
from property_units;

commit;
