/**
 * Db → App Model Mappers (Phase 13)
 * ==================================
 * Pure functions mapping database rows (`Db*` from `@/lib/supabase/types`)
 * onto the application types (`@/types/*`). Mappers are defensive: nullable
 * columns receive demo-safe defaults and `unknown` JSON columns are validated
 * before being cast, so the rest of the app can trust the resulting types.
 *
 * These are plain functions with no I/O — safe to import from API routes,
 * server components, and tests.
 */

import type {
  Geometry,
  LandParcel,
  Building,
  Floor,
  PropertyUnit,
  DemoSpatialIdentifier,
  DemoSpatialIdMetadata,
  OfficialUlpinMetadata,
} from '@/types/gis';
import type { VerificationRecord } from '@/types/verification';
import type { SpatialConflict } from '@/types/conflict';
import type { ActivityRecord } from '@/types/activity';
import type {
  DbParcel,
  DbBuilding,
  DbFloor,
  DbPropertyUnit,
  DbDemoSpatialId,
  DbVerification,
  DbConflict,
  DbActivity,
} from '@/lib/supabase/types';

// ── Geometry helpers ─────────────────────────────────────────────────────────

const GEOMETRY_TYPES = new Set(['Polygon', 'Point', 'LineString', 'MultiPolygon']);

/** Validates an unknown JSON value as a GeoJSON-style Geometry. */
export function asGeometry(value: unknown): Geometry | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const candidate = value as { type?: unknown; coordinates?: unknown };
  if (typeof candidate.type !== 'string' || !GEOMETRY_TYPES.has(candidate.type)) return null;
  if (!Array.isArray(candidate.coordinates)) return null;
  return {
    type: candidate.type as Geometry['type'],
    coordinates: candidate.coordinates as Geometry['coordinates'],
  };
}

/** Degenerate Point geometry used when a stored geometry is missing/invalid. */
function pointGeometry(lat: number, lng: number): Geometry {
  return { type: 'Point', coordinates: [lng, lat] };
}

// ── Metadata helpers ─────────────────────────────────────────────────────────

const DEFAULT_DEMO_ID_NOTE =
  'Demo spatial identifier generated by the 3D extraction pipeline. NOT an official ULPIN.';
const DEFAULT_ULPIN_NOTE =
  'Official ULPIN integration is a future external government API. Reference stays null until onboarded.';
const DEFAULT_ALGORITHM_VERSION = 'v1.0.0';

function asDemoSpatialIdMetadata(
  value: unknown,
  generatedAt: string,
  confidence: number,
): DemoSpatialIdMetadata {
  const v = (value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Partial<DemoSpatialIdMetadata>)
    : {}) as Partial<DemoSpatialIdMetadata>;
  return {
    label: 'Demo Spatial Identifier',
    // Hard guarantee: a demo spatial ID is never an official ULPIN.
    isOfficialUlpin: false,
    generatedAt: typeof v.generatedAt === 'string' ? v.generatedAt : generatedAt,
    algorithmVersion:
      typeof v.algorithmVersion === 'string' ? v.algorithmVersion : DEFAULT_ALGORITHM_VERSION,
    confidence: typeof v.confidence === 'number' ? v.confidence : confidence,
    note: typeof v.note === 'string' ? v.note : DEFAULT_DEMO_ID_NOTE,
  };
}

function asOfficialUlpinMetadata(value: unknown): OfficialUlpinMetadata {
  const v = (value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Partial<OfficialUlpinMetadata>)
    : {}) as Partial<OfficialUlpinMetadata>;
  return {
    // Hard guarantee: the government ULPIN API is not integrated yet.
    isIntegrated: false,
    integrationStatus:
      v.integrationStatus === 'EXTERNAL_GOVERNMENT_API' ? 'EXTERNAL_GOVERNMENT_API' : 'FUTURE',
    ...(typeof v.apiEndpoint === 'string' ? { apiEndpoint: v.apiEndpoint } : {}),
    note: typeof v.note === 'string' ? v.note : DEFAULT_ULPIN_NOTE,
  };
}

/** Extracts the conflict field-review request object, if valid. */
function asFieldReview(value: unknown): SpatialConflict['fieldReview'] {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined;
  const v = value as Record<string, unknown>;
  if (typeof v.requestedBy !== 'string' || typeof v.requestedAt !== 'string') return undefined;
  return {
    requestedBy: v.requestedBy,
    requestedAt: v.requestedAt,
    notes: typeof v.notes === 'string' ? v.notes : '',
  };
}

/** Extracts the conflict data-correction request object, if valid. */
function asCorrectionRequest(value: unknown): SpatialConflict['correctionRequest'] {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined;
  const v = value as Record<string, unknown>;
  if (
    typeof v.category !== 'string' ||
    typeof v.requestedBy !== 'string' ||
    typeof v.requestedAt !== 'string'
  ) {
    return undefined;
  }
  return {
    category: v.category,
    notes: typeof v.notes === 'string' ? v.notes : '',
    requestedBy: v.requestedBy,
    requestedAt: v.requestedAt,
  };
}

/** Extracts optional activity metadata object, if valid. */
function asMetadata(value: unknown): Record<string, unknown> | undefined {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return undefined;
  return value as Record<string, unknown>;
}

// ── Entity mappers ───────────────────────────────────────────────────────────

export function mapParcel(row: DbParcel): LandParcel {
  return {
    id: row.id,
    parcelNumber: row.parcel_number,
    location: row.location,
    district: row.district,
    state: row.state,
    area: Number(row.area),
    geometry: asGeometry(row.geometry) ?? pointGeometry(row.centroid_lat, row.centroid_lng),
    centroid: { lat: Number(row.centroid_lat), lng: Number(row.centroid_lng) },
    latitude: Number(row.latitude),
    longitude: Number(row.longitude),
    status: row.status,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export function mapBuilding(row: DbBuilding): Building {
  return {
    id: row.id,
    buildingCode: row.building_code,
    name: row.name,
    parcelId: row.parcel_id,
    address: row.address,
    latitude: Number(row.latitude),
    longitude: Number(row.longitude),
    height: row.height != null ? Number(row.height) : 0,
    totalFloors: row.total_floors ?? 0,
    builtUpArea: row.built_up_area != null ? Number(row.built_up_area) : 0,
    yearBuilt: row.year_built ?? 0,
    geometry: asGeometry(row.geometry) ?? pointGeometry(row.latitude, row.longitude),
    status: row.status,
  };
}

export function mapFloor(row: DbFloor): Floor {
  return {
    id: row.id,
    buildingId: row.building_id,
    floorNumber: row.floor_number,
    name: row.name,
    elevation: Number(row.elevation),
    area: Number(row.area),
    totalUnits: row.total_units ?? 0,
  };
}

export function mapPropertyUnit(row: DbPropertyUnit): PropertyUnit {
  const confidence = Number(row.confidence) || 0;
  return {
    id: row.id,
    propertyId: row.property_id,
    demoSpatialId: row.demo_spatial_id,
    officialUlpinReference: row.official_ulpin_reference ?? null,
    buildingId: row.building_id,
    floorId: row.floor_id,
    parcelId: row.parcel_id,
    unitNumber: row.unit_number,
    propertyType: row.property_type,
    area: Number(row.area),
    latitude: Number(row.latitude),
    longitude: Number(row.longitude),
    elevation: Number(row.elevation),
    geometry: asGeometry(row.geometry) ?? pointGeometry(row.latitude, row.longitude),
    ownerReferenceName: row.owner_reference_name,
    verificationStatus: row.verification_status,
    lastUpdated: row.last_updated,
    dataSource: row.data_source,
    demoSpatialIdMetadata: asDemoSpatialIdMetadata(
      row.demo_spatial_id_metadata,
      row.generated_at,
      confidence,
    ),
    officialUlpinMetadata: asOfficialUlpinMetadata(row.official_ulpin_metadata),
  };
}

export function mapDemoSpatialId(row: DbDemoSpatialId): DemoSpatialIdentifier {
  return {
    id: row.id,
    propertyUnitId: row.property_unit_id,
    demoId: row.demo_id,
    algorithm: row.algorithm,
    confidence: Number(row.confidence),
    // Hard guarantee: every demo spatial identifier is non-official.
    isOfficial: false,
    generatedAt: row.generated_at,
    note: row.note,
  };
}

export function mapVerification(row: DbVerification): VerificationRecord {
  const record: VerificationRecord = {
    id: row.id,
    propertyId: row.property_id,
    previousStatus: (row.previous_status?.trim()
      ? row.previous_status
      : 'Initial') as VerificationRecord['previousStatus'],
    newStatus: row.new_status as VerificationRecord['newStatus'],
    verifiedBy: row.verified_by,
    verifiedByRole: row.verified_by_role,
    verificationDate: row.verification_date,
    notes: row.notes,
    gpsMatched: row.gps_matched,
    boundaryMatched: row.boundary_matched,
    confidenceScore: Number(row.confidence_score),
    method: row.method,
    source: row.source,
  };
  if (row.photo_url) record.photoUrl = row.photo_url;
  return record;
}

export function mapConflict(row: DbConflict): SpatialConflict {
  const fieldReview = asFieldReview(row.field_review);
  const correctionRequest = asCorrectionRequest(row.correction_request);
  const conflict: SpatialConflict = {
    id: row.id,
    conflictNumber: row.conflict_number,
    type: row.type as SpatialConflict['type'],
    severity: row.severity,
    status: row.status,
    affectedPropertyIds: row.affected_property_ids ?? [],
    description: row.description,
    detectedAt: row.detected_at,
    geometry: asGeometry(row.geometry) ?? pointGeometry(0, 0),
  };
  if (row.parcel_id) conflict.parcelId = row.parcel_id;
  if (row.building_id) conflict.buildingId = row.building_id;
  if (row.resolved_at) conflict.resolvedAt = row.resolved_at;
  if (row.resolved_by) conflict.resolvedBy = row.resolved_by;
  if (row.resolution_notes) conflict.resolutionNotes = row.resolution_notes;
  if (row.last_action_at) conflict.lastActionAt = row.last_action_at;
  if (fieldReview) conflict.fieldReview = fieldReview;
  if (correctionRequest) conflict.correctionRequest = correctionRequest;
  return conflict;
}

export function mapActivity(row: DbActivity): ActivityRecord {
  return {
    id: row.id,
    type: row.type as ActivityRecord['type'],
    title: row.title,
    description: row.description ?? '',
    entityType: row.entity_type as ActivityRecord['entityType'],
    entityId: row.entity_id,
    timestamp: row.timestamp,
    user: row.user,
    userRole: row.user_role,
    status: row.status as ActivityRecord['status'],
    metadata: asMetadata(row.metadata),
  };
}