-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 007 — Demo Spatial IDs Table (Phase 13)
-- ─────────────────────────────────────────────────────────────────────────────
-- Stores the synthetic spatial identifiers generated by the demo algorithm.
-- Each demo spatial ID maps to exactly one property_unit.

create table public.demo_spatial_ids (
  id                uuid primary key default gen_random_uuid(),
  property_unit_id  uuid not null references public.property_units(id) on delete cascade,
  demo_id           text not null unique,
  algorithm         text not null,
  confidence        real not null check (confidence >= 0 and confidence <= 1),
  is_official       boolean not null default false,
  generated_at      timestamptz not null default now(),
  note              text
);

comment on table public.demo_spatial_ids is 'Demo spatial IDs (synthetic identifiers) linked to property units.';

create index if not exist idx_demo_spatial_ids_property_unit_id on public.demo_spatial_ids (property_unit_id);
create index if not exist idx_demo_spatial_ids_demo_id on public.demo_spatial_ids (demo_id);

alter table public.demo_spatial_ids enable row level security;

create policy "demo_spatial_ids are readable by all" on public.demo_spatial_ids
  for select using (true);

create policy "demo_spatial_ids are managed by officers and admins" on public.demo_spatial_ids
  for all using (true)
  with check (true);
