/**
 * Centralized Demo Spatial Identifier data
 * =========================================
 * One standalone record per PropertyUnit (20 total).
 *
 * Each demo spatial ID is explicitly marked `isOfficial: false` to guarantee
 * no consumer mistakes it for an official, government-issued ULPIN.
 *
 * IDs follow the pattern: DSID-001, DSID-002, ...
 */
import type { DemoSpatialIdentifier } from '@/types/gis';
import { MOCK_PROPERTIES } from '@/data/properties';
import { DEMO_SPATIAL_IDS } from '@/data/properties';

export const MOCK_DEMO_SPATIAL_IDS: DemoSpatialIdentifier[] = MOCK_PROPERTIES.map((p, i) => ({
  id: `DSID-${String(i + 1).padStart(3, '0')}`,
  propertyUnitId: p.id,
  demoId: p.demoSpatialId,
  algorithm: '3D-ULPIN/v2.4-spatial-hash',
  confidence: p.demoSpatialIdMetadata.confidence,
  isOfficial: false,
  generatedAt: p.demoSpatialIdMetadata.generatedAt,
  note: 'Demo spatial identifier — NOT an official ULPIN. Generated by AI 3D extraction pipeline.',
}));

/** Lookup by property unit ID. */
export const DEMO_SPATIAL_ID_BY_UNIT = new Map(
  MOCK_DEMO_SPATIAL_IDS.map((d) => [d.propertyUnitId, d]),
);

/** Export the list of all demo IDs for quick validation. */
export { DEMO_SPATIAL_IDS };
