/**
 * Centralized Property Unit (GIS) demo data
 * ==========================================
 * 20 vertical property units distributed across 3 buildings on 5 Pune parcels.
 *
 * Hierarchy:  LandParcel → Building → Floor → PropertyUnit
 *
 * IDs follow the pattern:
 *   - Property: PROP-102-0101
 *   - Demo Spatial ID: 3D-MH-PUN-102-0101
 *
 * IMPORTANT: `demoSpatialId` is a **Demo Spatial Identifier**, NOT an official
 * ULPIN. `officialUlpinReference` is always `null` (future government API
 * integration not yet live).
 */
import type {
  PropertyUnit,
  PropertyVerificationStatus,
  DataSource,
  DemoSpatialIdMetadata,
  OfficialUlpinMetadata,
  Geometry,
} from '@/types/gis';

// ── Shared helpers ──────────────────────────────────────────────────────────

const BUILDING_CODE_FOR: Record<string, string> = {
  'B-102': '102',
  'B-104': '104',
  'B-306': '306',
  'B-LR-A': 'LR-A',
  'B-LR-B': 'LR-B',
  'B-LR-C': 'LR-C',
  'B-LR-D': 'LR-D',
  'B-LR-E': 'LR-E',
};

function demoSpatialId(buildingId: string, unitNumber: string): string {
  return `3D-MH-PUN-${BUILDING_CODE_FOR[buildingId] ?? buildingId}-${unitNumber}`;
}

function demoMeta(generatedAt: string, confidence: number): DemoSpatialIdMetadata {
  return {
    label: 'Demo Spatial Identifier',
    isOfficialUlpin: false,
    generatedAt,
    algorithmVersion: '3D-ULPIN/v2.4-spatial-hash',
    confidence,
    note: 'Demo spatial ID generated by AI 3D extraction pipeline. NOT a legally-valid ULPIN. Official ULPIN integration pending government API onboarding.',
  };
}

function officialMeta(): OfficialUlpinMetadata {
  return {
    isIntegrated: false,
    integrationStatus: 'FUTURE',
    apiEndpoint: 'https://api.bhu-aadhaar.gov.in/v1/ulpin',
    note: 'Official ULPIN integration is a future / external government API integration. Until onboarded, officialUlpinReference remains null.',
  };
}

function point(lat: number, lng: number): Geometry {
  return { type: 'Point', coordinates: [lng, lat] };
}

interface UnitInput {
  id: string;
  propertyId: string;
  buildingId: string;
  floorId: string;
  parcelId: string;
  unitNumber: string;
  propertyType: 'RESIDENTIAL' | 'COMMERCIAL';
  area: number;
  lat: number;
  lng: number;
  elevation: number;
  ownerReferenceName: string;
  verificationStatus: PropertyVerificationStatus;
  lastUpdated: string;
  dataSource: DataSource;
  confidence: number;
  generatedAt: string;
}

function makeUnit(u: UnitInput): PropertyUnit {
  return {
    id: u.id,
    propertyId: u.propertyId,
    demoSpatialId: demoSpatialId(u.buildingId, u.unitNumber),
    officialUlpinReference: null,
    buildingId: u.buildingId,
    floorId: u.floorId,
    parcelId: u.parcelId,
    unitNumber: u.unitNumber,
    propertyType: u.propertyType,
    area: u.area,
    latitude: u.lat,
    longitude: u.lng,
    elevation: u.elevation,
    geometry: point(u.lat, u.lng),
    ownerReferenceName: u.ownerReferenceName,
    verificationStatus: u.verificationStatus,
    lastUpdated: u.lastUpdated,
    dataSource: u.dataSource,
    demoSpatialIdMetadata: demoMeta(u.generatedAt, u.confidence),
    officialUlpinMetadata: officialMeta(),
  };
}

const GENERATED_AT = '2025-03-01T08:00:00Z';
const NOW = new Date().toISOString();

// ── Building B-102: Green View Residency (parcel PARCEL-MH-PUN-001) ────────
// 10 registered units across 5 floors.
const B102_PID = 'PROP-MH-PUN-GVR-102';
const B102_PARCEL = 'PARCEL-MH-PUN-001';
const B102_LAT = 18.5318;
const B102_LNG = 73.8539;

const B104_PID = 'PROP-MH-PUN-SKA-104';
const B104_PARCEL = 'PARCEL-MH-PUN-002';
const B104_LAT = 18.5336;
const B104_LNG = 73.8657;

const B306_PID = 'prop-pun-003'; // links to existing PropertyItem
const B306_PARCEL = 'PARCEL-MH-PUN-003';
const B306_LAT = 18.5679;
const B306_LNG = 73.7749;

export const MOCK_PROPERTIES: PropertyUnit[] = [
  // ── B-102 Floor G ──
  makeUnit({
    id: 'PROP-102-G01', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-G',
    parcelId: B102_PARCEL, unitNumber: 'G-01', propertyType: 'RESIDENTIAL', area: 650,
    lat: B102_LAT + 0.0008, lng: B102_LNG - 0.0012, elevation: 2.5,
    ownerReferenceName: 'Rajesh V. Sharma', verificationStatus: 'Verified',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.96, generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-102-G02', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-G',
    parcelId: B102_PARCEL, unitNumber: 'G-02', propertyType: 'COMMERCIAL', area: 420,
    lat: B102_LAT + 0.0008, lng: B102_LNG + 0.0008, elevation: 2.5,
    ownerReferenceName: 'Apex Banking Corp', verificationStatus: 'Pending',
    lastUpdated: NOW, dataSource: 'SURVEY_RECORD', confidence: 0.91, generatedAt: GENERATED_AT,
  }),
  // ── B-102 Floor 1 ──
  makeUnit({
    id: 'PROP-102-0101', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-1',
    parcelId: B102_PARCEL, unitNumber: '0101', propertyType: 'RESIDENTIAL', area: 850,
    lat: B102_LAT + 0.0012, lng: B102_LNG - 0.0008, elevation: 6.0,
    ownerReferenceName: 'Priya R. Kulkarni', verificationStatus: 'Verified',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.95, generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-102-0102', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-1',
    parcelId: B102_PARCEL, unitNumber: '0102', propertyType: 'RESIDENTIAL', area: 1050,
    lat: B102_LAT + 0.0012, lng: B102_LNG + 0.0004, elevation: 6.0,
    ownerReferenceName: 'Arjun Mehta', verificationStatus: 'Verified',
    lastUpdated: NOW, dataSource: 'DRONE_SCAN', confidence: 0.97, generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-102-0103', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-1',
    parcelId: B102_PARCEL, unitNumber: '0103', propertyType: 'RESIDENTIAL', area: 850,
    lat: B102_LAT + 0.0012, lng: B102_LNG + 0.0016, elevation: 6.0,
    ownerReferenceName: 'Neha Verma', verificationStatus: 'Under Review',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.88, generatedAt: GENERATED_AT,
  }),
  // ── B-102 Floor 2 ──
  makeUnit({
    id: 'PROP-102-0201', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-2',
    parcelId: B102_PARCEL, unitNumber: '0201', propertyType: 'RESIDENTIAL', area: 1050,
    lat: B102_LAT - 0.0006, lng: B102_LNG - 0.0005, elevation: 9.5,
    ownerReferenceName: 'Venkat Rao Deshmukh', verificationStatus: 'Verified',
    lastUpdated: NOW, dataSource: 'DRONE_SCAN', confidence: 0.94, generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-102-0202', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-2',
    parcelId: B102_PARCEL, unitNumber: '0202', propertyType: 'RESIDENTIAL', area: 850,
    lat: B102_LAT - 0.0006, lng: B102_LNG + 0.0009, elevation: 9.5,
    ownerReferenceName: 'Farah Ansari', verificationStatus: 'Under Review',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.85, generatedAt: GENERATED_AT,
  }),
  // ── B-102 Floor 3 ──
  makeUnit({
    id: 'PROP-102-0301', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-3',
    parcelId: B102_PARCEL, unitNumber: '0301', propertyType: 'RESIDENTIAL', area: 1050,
    lat: B102_LAT + 0.0020, lng: B102_LNG - 0.0003, elevation: 13.0,
    ownerReferenceName: 'Karthik Subramaniam', verificationStatus: 'Verified',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.96, generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-102-0302', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-3',
    parcelId: B102_PARCEL, unitNumber: '0302', propertyType: 'RESIDENTIAL', area: 850,
    lat: B102_LAT + 0.0020, lng: B102_LNG + 0.0012, elevation: 13.0,
    ownerReferenceName: 'Sunita V. Deshpande', verificationStatus: 'Under Review',
    lastUpdated: NOW, dataSource: 'SURVEY_RECORD', confidence: 0.87, generatedAt: GENERATED_AT,
  }),
  // ── B-102 Floor 4 ──
  makeUnit({
    id: 'PROP-102-0401', propertyId: B102_PID, buildingId: 'B-102', floorId: 'FLOOR-102-4',
    parcelId: B102_PARCEL, unitNumber: '0401', propertyType: 'RESIDENTIAL', area: 850,
    lat: B102_LAT - 0.0014, lng: B102_LNG + 0.0010, elevation: 16.5,
    ownerReferenceName: 'Mahesh K. Joshi', verificationStatus: 'Reinspection Required',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.72, generatedAt: GENERATED_AT,
  }),
];

export const B102_PID_REF = B102_PID;

// ── Building B-104: Shree Krishna Arcade (parcel PARCEL-MH-PUN-002) ───────
// 6 registered units across 5 floors.
MOCK_PROPERTIES.push(
  // ── B-104 Floor G ──
  makeUnit({
    id: 'PROP-104-G01', propertyId: B104_PID, buildingId: 'B-104', floorId: 'FLOOR-104-G',
    parcelId: B104_PARCEL, unitNumber: 'G-01', propertyType: 'COMMERCIAL', area: 520,
    lat: B104_LAT + 0.0005, lng: B104_LNG - 0.0006, elevation: 2.0,
    ownerReferenceName: 'Shree Krishna Traders', verificationStatus: 'Verified',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.93, generatedAt: GENERATED_AT,
  }),
  // ── B-104 Floor 1 ──
  makeUnit({
    id: 'PROP-104-0101', propertyId: B104_PID, buildingId: 'B-104', floorId: 'FLOOR-104-1',
    parcelId: B104_PARCEL, unitNumber: '0101', propertyType: 'RESIDENTIAL', area: 780,
    lat: B104_LAT + 0.0007, lng: B104_LNG - 0.0004, elevation: 5.5,
    ownerReferenceName: 'Ramesh B. Patil', verificationStatus: 'Verified',
    lastUpdated: NOW, dataSource: 'DRONE_SCAN', confidence: 0.92, generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-104-0102', propertyId: B104_PID, buildingId: 'B-104', floorId: 'FLOOR-104-1',
    parcelId: B104_PARCEL, unitNumber: '0102', propertyType: 'RESIDENTIAL', area: 820,
    lat: B104_LAT + 0.0007, lng: B104_LNG + 0.0004, elevation: 5.5,
    ownerReferenceName: 'Sneha R. K.', verificationStatus: 'Pending',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.88, generatedAt: GENERATED_AT,
  }),
  // ── B-104 Floor 2 ──
  makeUnit({
    id: 'PROP-104-0201', propertyId: B104_PID, buildingId: 'B-104', floorId: 'FLOOR-104-2',
    parcelId: B104_PARCEL, unitNumber: '0201', propertyType: 'RESIDENTIAL', area: 780,
    lat: B104_LAT - 0.0003, lng: B104_LNG + 0.0002, elevation: 8.5,
    ownerReferenceName: 'Amit Desai', verificationStatus: 'Pending',
    lastUpdated: NOW, dataSource: 'SURVEY_RECORD', confidence: 0.89, generatedAt: GENERATED_AT,
  }),
  // ── B-104 Floor 3 ──
  makeUnit({
    id: 'PROP-104-0301', propertyId: B104_PID, buildingId: 'B-104', floorId: 'FLOOR-104-3',
    parcelId: B104_PARCEL, unitNumber: '0301', propertyType: 'COMMERCIAL', area: 650,
    lat: B104_LAT + 0.0010, lng: B104_LNG, elevation: 11.5,
    ownerReferenceName: 'Global Tech Solutions Pvt Ltd', verificationStatus: 'Pending',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.86, generatedAt: GENERATED_AT,
  }),
  // ── B-104 Floor 4 ──
  makeUnit({
    id: 'PROP-104-0401', propertyId: B104_PID, buildingId: 'B-104', floorId: 'FLOOR-104-4',
    parcelId: B104_PARCEL, unitNumber: '0401', propertyType: 'COMMERCIAL', area: 650,
    lat: B104_LAT - 0.0008, lng: B104_LNG - 0.0010, elevation: 14.5,
    ownerReferenceName: 'Innovate Labs India', verificationStatus: 'Rejected',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.65, generatedAt: GENERATED_AT,
  }),
);

// ── Building B-306: Tech Tower (parcel PARCEL-MH-PUN-003) ──────────────────
// 4 registered units across 4 floors. propertyId links to existing PropertyItem.
MOCK_PROPERTIES.push(
  // ── B-306 Floor G ──
  makeUnit({
    id: 'PROP-306-G01', propertyId: B306_PID, buildingId: 'B-306', floorId: 'FLOOR-306-G',
    parcelId: B306_PARCEL, unitNumber: 'G-01', propertyType: 'COMMERCIAL', area: 480,
    lat: B306_LAT + 0.0006, lng: B306_LNG - 0.0005, elevation: 2.5,
    ownerReferenceName: 'Cafe Bahar Owner', verificationStatus: 'Pending',
    lastUpdated: NOW, dataSource: 'SURVEY_RECORD', confidence: 0.88, generatedAt: GENERATED_AT,
  }),
  // ── B-306 Floor 1 ──
  makeUnit({
    id: 'PROP-306-0101', propertyId: B306_PID, buildingId: 'B-306', floorId: 'FLOOR-306-1',
    parcelId: B306_PARCEL, unitNumber: '0101', propertyType: 'COMMERCIAL', area: 1200,
    lat: B306_LAT + 0.0008, lng: B306_LNG - 0.0002, elevation: 6.0,
    ownerReferenceName: 'TCS Ltd', verificationStatus: 'Verified',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.95, generatedAt: GENERATED_AT,
  }),
  // ── B-306 Floor 2 ──
  makeUnit({
    id: 'PROP-306-0201', propertyId: B306_PID, buildingId: 'B-306', floorId: 'FLOOR-306-2',
    parcelId: B306_PARCEL, unitNumber: '0201', propertyType: 'COMMERCIAL', area: 950,
    lat: B306_LAT + 0.0012, lng: B306_LNG + 0.0005, elevation: 10.0,
    ownerReferenceName: 'WIPRO Ltd', verificationStatus: 'Reinspection Required',
    lastUpdated: NOW, dataSource: 'DRONE_SCAN', confidence: 0.78, generatedAt: GENERATED_AT,
  }),
  // ── B-306 Floor 3 ──
  makeUnit({
    id: 'PROP-306-0301', propertyId: B306_PID, buildingId: 'B-306', floorId: 'FLOOR-306-3',
    parcelId: B306_PARCEL, unitNumber: '0301', propertyType: 'COMMERCIAL', area: 950,
    lat: B306_LAT - 0.0004, lng: B306_LNG + 0.0008, elevation: 14.0,
    ownerReferenceName: 'TechStart Innovations', verificationStatus: 'Pending',
    lastUpdated: NOW, dataSource: 'AI_EXTRACTION', confidence: 0.85, generatedAt: GENERATED_AT,
  }),
);

// ── Kolte Patil Life Republic Penthouses (parcel PARCEL-MH-PUN-074) ──────
const LR_PID = 'PROP-LR-B-0402';
const LR_PARCEL = 'PARCEL-MH-PUN-074';
const LR_LAT = 18.6172;
const LR_LNG = 73.7141;

MOCK_PROPERTIES.push(
  // ── Tower B, Floor 4 (Featured Sample Property: Flat 402) ──
  makeUnit({
    id: 'PROP-LR-B-0402',
    propertyId: LR_PID,
    buildingId: 'B-LR-B',
    floorId: 'FLOOR-LR-B-04',
    parcelId: LR_PARCEL,
    unitNumber: '402',
    propertyType: 'RESIDENTIAL',
    area: 1050,
    lat: 18.6178,
    lng: 73.7138,
    elevation: 12.4, // Floor 4 * 3.1m
    ownerReferenceName: 'Vikramaditya S. Kulkarni',
    verificationStatus: 'Verified',
    lastUpdated: NOW,
    dataSource: 'AI_EXTRACTION',
    confidence: 0.98,
    generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-LR-B-0401',
    propertyId: 'PROP-LR-B-0401',
    buildingId: 'B-LR-B',
    floorId: 'FLOOR-LR-B-04',
    parcelId: LR_PARCEL,
    unitNumber: '401',
    propertyType: 'RESIDENTIAL',
    area: 1050,
    lat: 18.6178,
    lng: 73.7137,
    elevation: 12.4,
    ownerReferenceName: 'Ananya Deshmukh',
    verificationStatus: 'Verified',
    lastUpdated: NOW,
    dataSource: 'AI_EXTRACTION',
    confidence: 0.95,
    generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-LR-B-0403',
    propertyId: 'PROP-LR-B-0403',
    buildingId: 'B-LR-B',
    floorId: 'FLOOR-LR-B-04',
    parcelId: LR_PARCEL,
    unitNumber: '403',
    propertyType: 'RESIDENTIAL',
    area: 1250,
    lat: 18.6179,
    lng: 73.7138,
    elevation: 12.4,
    ownerReferenceName: 'Rahul M. Joshi',
    verificationStatus: 'Under Review',
    lastUpdated: NOW,
    dataSource: 'DRONE_SCAN',
    confidence: 0.94,
    generatedAt: GENERATED_AT,
  }),
  makeUnit({
    id: 'PROP-LR-B-0404',
    propertyId: 'PROP-LR-B-0404',
    buildingId: 'B-LR-B',
    floorId: 'FLOOR-LR-B-04',
    parcelId: LR_PARCEL,
    unitNumber: '404',
    propertyType: 'RESIDENTIAL',
    area: 1250,
    lat: 18.6179,
    lng: 73.7139,
    elevation: 12.4,
    ownerReferenceName: 'Meera N. Patel',
    verificationStatus: 'Pending',
    lastUpdated: NOW,
    dataSource: 'SURVEY_RECORD',
    confidence: 0.91,
    generatedAt: GENERATED_AT,
  }),
  // ── Tower B, Ground Floor ──
  makeUnit({
    id: 'PROP-LR-B-G01',
    propertyId: 'PROP-LR-B-G01',
    buildingId: 'B-LR-B',
    floorId: 'FLOOR-LR-B-G',
    parcelId: LR_PARCEL,
    unitNumber: 'G-01',
    propertyType: 'COMMERCIAL',
    area: 850,
    lat: 18.6178,
    lng: 73.7138,
    elevation: 0.0,
    ownerReferenceName: 'Life Republic Concierge Desk',
    verificationStatus: 'Verified',
    lastUpdated: NOW,
    dataSource: 'SURVEY_RECORD',
    confidence: 0.99,
    generatedAt: GENERATED_AT,
  }),
  // ── Tower B, Floor 20 (Sky Penthouse) ──
  makeUnit({
    id: 'PROP-LR-B-2001',
    propertyId: 'PROP-LR-B-2001',
    buildingId: 'B-LR-B',
    floorId: 'FLOOR-LR-B-20',
    parcelId: LR_PARCEL,
    unitNumber: '2001',
    propertyType: 'RESIDENTIAL',
    area: 2100,
    lat: 18.6178,
    lng: 73.7138,
    elevation: 62.0,
    ownerReferenceName: 'Siddharth R. Singhania',
    verificationStatus: 'Verified',
    lastUpdated: NOW,
    dataSource: 'AI_EXTRACTION',
    confidence: 0.97,
    generatedAt: GENERATED_AT,
  }),
  // ── Tower A Units ──
  makeUnit({
    id: 'PROP-LR-A-0101',
    propertyId: 'PROP-LR-A-0101',
    buildingId: 'B-LR-A',
    floorId: 'FLOOR-LR-A-01',
    parcelId: LR_PARCEL,
    unitNumber: '101',
    propertyType: 'RESIDENTIAL',
    area: 1100,
    lat: 18.6174,
    lng: 73.7132,
    elevation: 3.1,
    ownerReferenceName: 'Pooja Agarwal',
    verificationStatus: 'Verified',
    lastUpdated: NOW,
    dataSource: 'AI_EXTRACTION',
    confidence: 0.96,
    generatedAt: GENERATED_AT,
  }),
  // ── Tower C Units ──
  makeUnit({
    id: 'PROP-LR-C-0101',
    propertyId: 'PROP-LR-C-0101',
    buildingId: 'B-LR-C',
    floorId: 'FLOOR-LR-C-01',
    parcelId: LR_PARCEL,
    unitNumber: '101',
    propertyType: 'RESIDENTIAL',
    area: 1150,
    lat: 18.6179,
    lng: 73.7149,
    elevation: 3.1,
    ownerReferenceName: 'Kunal Kapoor',
    verificationStatus: 'Verified',
    lastUpdated: NOW,
    dataSource: 'DRONE_SCAN',
    confidence: 0.95,
    generatedAt: GENERATED_AT,
  }),
  // ── Tower D Units ──
  makeUnit({
    id: 'PROP-LR-D-0101',
    propertyId: 'PROP-LR-D-0101',
    buildingId: 'B-LR-D',
    floorId: 'FLOOR-LR-D-01',
    parcelId: LR_PARCEL,
    unitNumber: '101',
    propertyType: 'RESIDENTIAL',
    area: 980,
    lat: 18.6170,
    lng: 73.7130,
    elevation: 3.1,
    ownerReferenceName: 'Deepak Shah',
    verificationStatus: 'Verified',
    lastUpdated: NOW,
    dataSource: 'AI_EXTRACTION',
    confidence: 0.93,
    generatedAt: GENERATED_AT,
  }),
  // ── Tower E Units ──
  makeUnit({
    id: 'PROP-LR-E-0101',
    propertyId: 'PROP-LR-E-0101',
    buildingId: 'B-LR-E',
    floorId: 'FLOOR-LR-E-01',
    parcelId: LR_PARCEL,
    unitNumber: '101',
    propertyType: 'RESIDENTIAL',
    area: 1200,
    lat: 18.6166,
    lng: 73.7148,
    elevation: 3.1,
    ownerReferenceName: 'Aarav Nair',
    verificationStatus: 'Verified',
    lastUpdated: NOW,
    dataSource: 'AI_EXTRACTION',
    confidence: 0.96,
    generatedAt: GENERATED_AT,
  }),
);

// ── Indexes ────────────────────────────────────────────────────────────────

export const PROPERTY_BY_ID = new Map(MOCK_PROPERTIES.map((p) => [p.id, p]));
export const PROPERTIES_BY_BUILDING = MOCK_PROPERTIES.reduce(
  (acc, p) => {
    (acc[p.buildingId] = acc[p.buildingId] || []).push(p);
    return acc;
  },
  {} as Record<string, PropertyUnit[]>,
);
export const PROPERTIES_BY_PARCEL = MOCK_PROPERTIES.reduce(
  (acc, p) => {
    (acc[p.parcelId] = acc[p.parcelId] || []).push(p);
    return acc;
  },
  {} as Record<string, PropertyUnit[]>,
);

/** All demo spatial IDs (always non-official). */
export const DEMO_SPATIAL_IDS = MOCK_PROPERTIES.map((p) => p.demoSpatialId);
